import type { PositionTargetConfig } from '../management/target-position.js';
import type { ManagementProfile } from '../management/types.js';

export interface IndicatorConfig {
  version: string;
  type: string;
  created_at: string;
  ema_fast: number;
  ema_mid: number;
  ema_slow: number;
  rsi_period: number;
  atr_period: number;
  volume_sma_period: number;
  min_confidence: number;
  max_confidence: number;
  min_rr: number;
  max_risk_per_trade_pct: number;
  max_daily_loss_pct: number;
  max_consecutive_losses: number;
  account_equity: number;
  time_stop_minutes: number;
  time_stop_max_r_pre_t1: number;
  time_stop_max_r_post_t1: number;
  analysis_interval_seconds: number;
  in_position_monitor_seconds: number;
  opening_range_minutes: number;
  trail_ticks_post_t1: number;
  breakeven_trigger_r: number;
  pre_t1_trail_trigger_r: number;
  pre_t1_trail_distance_ticks: number;
  pt1_offset_pts: number;
  pt2_offset_pts: number;
  pt1_exit_fraction: number;
  pt2_exit_fraction: number;
  pt1_move_to_be: boolean;
  pt1_activate_trailing: boolean;
  enable_momentum_continuation: boolean;
  enable_opening_drive: boolean;
  enable_failed_or_break: boolean;
  dual_min_score: number;
  dual_score_margin: number;
  dual_choppy_extra_margin: number;
  cooldown_bars: number;
  no_same_bar_reversal: boolean;
  max_net_position_per_symbol?: number;
  position_target?: PositionTargetConfig;
  management_profiles?: Record<string, ManagementProfile>;
  management_profile_variants?: Record<string, Record<string, Partial<ManagementProfile>>>;
  active_management_variant?: string | null;
}
