import type {
  ActiveStrategyId,
  RegisteredInactiveStrategyId,
} from './strategy-ids.js';

/**
 * Generated by the strategy-generation loop candidate emitter.
 *
 * Keep the default checked-in state empty and fail-closed: generated candidates
 * must be explicitly materialized here before the runtime can parse them.
 */
export const GENERATED_CANDIDATE_STRATEGY_IDS = [] as const;

export type GeneratedCandidateStrategyId =
  (typeof GENERATED_CANDIDATE_STRATEGY_IDS)[number];

export type GeneratedCandidateBaseStrategyId =
  | ActiveStrategyId
  | RegisteredInactiveStrategyId;

/**
 * Maps each generated candidate strategy id to the static family/base strategy
 * whose generator semantics it reuses. This file is intentionally static TS
 * rather than runtime discovery so unknown candidate IDs still reject.
 */
export const GENERATED_CANDIDATE_BASE_STRATEGY_IDS = {} as const satisfies
  Readonly<Record<GeneratedCandidateStrategyId, GeneratedCandidateBaseStrategyId>>;

const GENERATED_CANDIDATE_STRATEGY_ID_SET = new Set<string>(
  GENERATED_CANDIDATE_STRATEGY_IDS,
);

export function isGeneratedCandidateStrategyId(
  value: string,
): value is GeneratedCandidateStrategyId {
  return GENERATED_CANDIDATE_STRATEGY_ID_SET.has(value);
}

export function getGeneratedCandidateBaseStrategyId(
  value: GeneratedCandidateStrategyId,
): GeneratedCandidateBaseStrategyId {
  const baseStrategyId = (
    GENERATED_CANDIDATE_BASE_STRATEGY_IDS as Readonly<Record<string, GeneratedCandidateBaseStrategyId>>
  )[value];
  if (baseStrategyId === undefined) {
    throw new Error(`generated candidate ${value} is missing a base strategy mapping`);
  }
  return baseStrategyId;
}
